language: rust
sudo: false
os:
- linux
dist: trusty

addons:
  apt:
    packages:
      - musl-tools

rust:
- stable
- beta
- nightly


# Add a release build.
matrix:
  include:
    - rust: stable
      env: TARGET=x86_64-unknown-linux-musl DEPLOY=1

cache: cargo

script:
- |
  if [[ "$DEPLOY" = 1 ]]; then
    rustup target add $TARGET &&
    cargo build --release --target $TARGET
  else
    cargo build -v &&
    cargo test -v
  fi

before_deploy:
  - strip target/$TARGET/release/tracetree
  - cd target/$TARGET/release/ && tar czvf ../../../tracetree-$TRAVIS_TAG-$TARGET.tar.gz tracetree

env:
  global:
  - RUST_BACKTRACE=1
deploy:
  provider: releases
  api_key:
    secure: kImz2Be7NJAjGofluPUZGAB/fG/fscr+0kr9KVQLqY36qx4+tueLk9+WrzVXqkWS+a1V0MwHgTpu0wTbXYPcpeDWkonKgihgb3LTTAsYcs4GRPV/u3dvNFJDYnrn96Sk81ysD6nq3PZSx7RVT8rqIkP30Sh1jovrq0iOBOuABKqPujRi/Wozc15Y5wPxgHAXcZpdKmeZpG46rIEM2+PFZxEV2mdHEQSIhy/Q7vmDea4UJGdKiXmUvrtTuFzBcHZ0ZEZu59vzZuwrZS2Kie05hj405M1ITe6eNwaNbvY+9Li+8vymbepOEIpXCpwyGr49ELimPz6FNU+Fi6kPORMgjoIll5og4XRaYq8gsJ69Ie64CC8QXYDrAaY5kHLKrMg46HMHmQoYdUgjwnAaTFpxhwAOwD+Ya5tHlOr4Yb+JQVVGNgQeDfSOZCyIzwu0Wwfugu60bBH548ZIj3ibnkyPFPxIrcekAxwP8PyC8oIxQ04DXQ3KSkZErD6syWcPw2dWtQZzGG6LRRT5fn3bJm53ugfi1pz6/e4n486qGzacJVekyHJWaxdA3oZjXsQVTcGjvkiYMr+wWAj5HhZwVWskCReefKRHw6NR5YYg7nVg2WhP5qrwcB6Nc7XFuiOU3koslUnT40pAnya33IwhFAQBQzWh/G0gFOzHmfhlMjr/N+g=
  file: tracetree-$TRAVIS_TAG-linux-x86_64.tar.gz
  on:
    repo: luser/tracetree
    condition: $DEPLOY = 1
    tags: true
  skip_cleanup: true
