[package]
name = "tracetree"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]

[dependencies]
env_logger = "0.3.5"
libc = "0.2.15"
log = "0.3.6"
nix = { path = "../nix" }
spawn-ptrace = { path = "../spawn-ptrace" }
